name: AAA-FINAL-TSP-GLS

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to run"
        required: true
        default: "reevo_run1"

permissions:
  contents: read

jobs:
  run-tsp-gls:
    name: TSP-GLS [ReEvo]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["50", "100", "200", "500"]

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: SETUP PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: INSTALL DEPENDENCIES
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN TSP${{ matrix.scripts }}
        run: |
          echo "Running ${{ matrix.scripts }}..."
          python FINAL/${{ github.event.inputs.command }}.py ${{ matrix.scripts }}
