name: MATRIX-BPP-ACO [EoH]

on: workflow_dispatch

permissions:
  contents: read

jobs:
  run-tsp-aco:
    name: MATRIX-BPP-ACO [EoH]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["200", "400", "600", "800", "1000"]

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: SETUP PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: INSTALL DEPENDENCIES
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN BPP${{ matrix.scripts }}
        run: |
          echo "Running ${{ matrix.scripts }}..."
          python bpp_aco/eoh.py ${{ matrix.scripts }}
