name: MOTIF SOLVER

on:
  workflow_dispatch:
    inputs:
      solver:
        description: "Solver"
        required: true
        default: "tsp_aco"
        type: choice
        options:
          - tsp_aco
          - tsp_ga
          - tsp_gls
          - op_aco
          - bpp_aco
          - cvrp_aco
      outer_iterations:
        description: "Outer Iterations"
        required: true
        default: "20"
      inner_iterations:
        description: "Inner Iterations"
        required: true
        default: "10"
      model:
        description: "LLM"
        required: true
        default: "gpt-4o-mini"
        type: choice
        options:
          - gpt-4o-mini
          - gpt-4o
          - gpt-4.1

permissions:
  contents: read

jobs:
  run-optimization:
    name: MCTS Optimization
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          repository: HaiAu2501/MOTIF
          token: ${{ secrets.CHECKOUT_TOKEN }}
          ref: turn-based

      - name: SETUP PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: INSTALL DEPENDENCIES
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN OPTIMIZATION
        run: |
          echo "Running optimization with solver=${{ github.event.inputs.solver }}..."
          echo "Running optimization with outer_iterations=${{ github.event.inputs.outer_iterations }} and inner_iterations=${{ github.event.inputs.inner_iterations }} and model=${{ github.event.inputs.model }}..."
          python main.py \
            solver=${{ github.event.inputs.solver }} \
            mcts.outer_iterations=${{ github.event.inputs.outer_iterations }} \
            mcts.inner_iterations=${{ github.event.inputs.inner_iterations }} \
            llm.model=${{ github.event.inputs.model }}

      - name: UPLOAD RESULTS
        uses: actions/upload-artifact@v4
        with:
          name: optimization-results
          path: |
            results/
          if-no-files-found: warn
          retention-days: 90
