name: MCTS Optimization

on:
  workflow_dispatch:
    inputs:
      iteration:
        description: "Number of iterations"
        required: true
        default: "10"
      model:
        description: "LLM model name"
        required: true
        default: "gpt-4o-mini"
        type: choice
        options:
          - gpt-4o-mini
          - gpt-4o
          - gpt-4.1

permissions:
  contents: read

jobs:
  run-optimization:
    name: MCTS Optimization
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: HaiAu2501/MERO
          token: ${{ secrets.CHECKOUT_TOKEN }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run optimization
        run: |
          echo "Running optimization with iteration=${{ github.event.inputs.iteration }} and model=${{ github.event.inputs.model }}..."
          python main.py mcts.iteration=${{ github.event.inputs.iteration }} llm.model=${{ github.event.inputs.model }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: optimization-results
          path: |
            results/
            logger/
            outputs/
          if-no-files-found: warn
          retention-days: 90
