name: TSP-ACO by ReEvo

on: workflow_dispatch

permissions:
  contents: read

jobs:
  run-tsp-aco-reevo:
    name: TSP-ACO by ReEvo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["200", "500", "1000"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.scripts }}
        run: |
          echo "Running TSP${{ matrix.scripts }}..."
          python tsp_aco_mero/reevo.py ${{ matrix.scripts }}
