name: TSP-ACO by ReEvo

on:
  workflow_dispatch:
    inputs:
      seed:
        description: "Random seed"
        required: true
        default: "0"
        type: choice
        options:
          - 0
          - 1234
          - 42

permissions:
  contents: read

jobs:
  run-tsp-aco-reevo:
    name: TSP-ACO by ReEvo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["20", "50", "100"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.scripts }}
        run: |
          echo "Running TSP${{ matrix.scripts }}..."
          python tsp_aco_mero/reevo.py ${{ matrix.scripts }} ${{ github.event.inputs.seed }}
