name: TSP-ACO-v0 by MERO

on:
  workflow_dispatch:
    inputs:
      n_ants:
        description: "Number of ants"
        required: true
        default: "10"
      n_interations:
        description: "Number of iterations"
        required: true
        default: "100"

permissions:
  contents: read

jobs:
  run-tsp-aco-mero:
    name: TSP-ACO by MERO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["200", "500", "1000"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TSP${{ matrix.scripts }}
        run: |
          echo "Running TSP${{ matrix.scripts }} on n_ants=${{ github.event.inputs.n_ants }} and n_interations=${{ github.event.inputs.n_interations }}..."
          python tsp_aco_mero/test_v0.py ${{ matrix.scripts }} ${{ github.event.inputs.n_ants }} ${{ github.event.inputs.n_interations }}
