name: MATRIX-TSP-ACO [MOTIF]

on: workflow_dispatch

permissions:
  contents: read

jobs:
  run-tsp-aco:
    name: MATRIX-TSP-ACO [MOTIF]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["50"]

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: SETUP PYTHON
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: INSTALL DEPENDENCIES
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RUN TSP${{ matrix.scripts }}
        run: |
          echo "Running ${{ matrix.scripts }}..."
          python tsp_aco/eval.py ${{ matrix.scripts }}
