name: MERO on Large-scale Instances

on:
  workflow_dispatch:
    inputs:
      solution:
        description: "Solution file"
        required: true
        default: "solution_83"
        type: choice
        options:
          - solution_82
          - solution_83
          - solution_94

permissions:
  contents: read

jobs:
  run-tsp-aco-mero:
    name: MERO on Large-scale Instances
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["200", "500", "1000"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.scripts }}
        run: |
          echo "Running TSP${{ matrix.scripts }}..."
          python tsp_aco_mero/test.py ${{ github.event.inputs.solution }} ${{ matrix.scripts }}
