name: TSP-ACO by MERO

on: workflow_dispatch

permissions:
  contents: read

jobs:
  run-tsp-aco-mero:
    name: TSP-ACO by MERO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: ["solution_3", "solution_4"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.scripts }}
        run: |
          echo "Running ${{ matrix.scripts }}..."
          python tsp_aco_mero/main.py ${{ matrix.scripts }}
